version: '3.8'

services:
  astro:
    image: astronomerinc/ap-airflow:latest
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./astroboy_project/dags:/usr/local/airflow/dags
      - ./astroboy_project/plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"

  meltano:
    image: meltano/meltano:latest
    volumes:
      - ./my_metanol_project:/project
    working_dir: /project
    command: meltano ui
    ports:
      - "5000:5000"
